### ISSUE TITLE
simple example from README won't compile

### ISSUE THREAD

**Issue by jeanmenezes** [noteflakes/lyp-structure#1]
Hello,

when trying to compile the simple example as listed in the README file (using `lyp`), I  get the following error message:

```
Lyp 1.3.8
GNU LilyPond 2.19.81
Processing `/tmp/lyp/wrappers/structure.ly'
Parsing...
path: aria
/home/jean/.lyp/packages/structure/lib/support.scm:21:23: In procedure hash-map->list in expression (hash-map->list (lambda # k) h):
/home/jean/.lyp/packages/structure/lib/support.scm:21:23: Wrong type argument in position 2: #f
```

Any thoughts on this?

Thanks for the attention!

**Comment by noteflakes** [comment]
The example was missing a `\cd "aria"` command, see the [updated example](https://github.com/lyp-packages/structure#a-simple-example). Please note that this is a WIP, and it's been a while since I've worked on it.
